### ISSUE TITLE
unused label in fitpack_parametric.f90

### ISSUE THREAD

**Issue by Beliavsky** [perazz/fitpack#13]
`gfortran -c -Wall -Wextra fitpack_parametric.f90`

says

```
fitpack_parametric.f90:439:8:

  439 |        1 call fitpack_error_handling(ierr0,ierr,'evaluate derivative')
      |        1
Warning: Label 1 at (1) defined but not used [-Wunused-label]
```

and I confirmed that the file compiles when the label is removed.

**Comment by perazz** [comment]
Thank you @Beliavsky, fixed in https://github.com/perazz/fitpack/commit/6920e5934f67e185cd021d172ede17722c0913e6.
