### ISSUE TITLE
Some tests hanging?

### ISSUE THREAD

**Issue by jacobwilliams** [perazz/fitpack#5]
Tests 13, 14, 16, 20, 24, 28, and 29 seems to be hanging when I run them. Are they stuck in an infinite loop or do they really just take a long time to run?

**Comment by perazz** [comment]
It seems like they relate to some `read(5,fmt)` commands, so they expect input data I guess?

**Comment by jacobwilliams** [comment]
Ah! Yes, that's what's happening. It looks like the intent was to pipe in the contents of [these data files](https://netlib.org/dierckx/ex/):

 * [dapasu](https://netlib.org/dierckx/ex/dapasu)
 * [dapogr](https://netlib.org/dierckx/ex/dapogr)
 * [dapola](https://netlib.org/dierckx/ex/dapola)
 * [daregr](https://netlib.org/dierckx/ex/daregr)
 * [daspgr](https://netlib.org/dierckx/ex/daspgr)
 * [dasphe](https://netlib.org/dierckx/ex/dasphe)
 * [dasurf](https://netlib.org/dierckx/ex/dasurf)

Probably the best thing would be to just move the contents of these files into parameter arrays in the code, then the test are self contained and we don't have to worry about reading files.

**Comment by perazz** [comment]
According to the [netlib page](https://netlib.org/dierckx/readme) 

```
Some of the test programs need some
input data. These can be found in the files with initials da, e.g. the program
in mnpasu.f needs the data which are stored in dapasu, etc.
```

so `da*` stands for "data", I have no idea what `mn*` stands for but I guess `dapasu` is the data for program `mnpasu`, etc.

**Comment by perazz** [comment]
Maybe `mn*` is `main`...

**Comment by perazz** [comment]
Added datafiles for test 13, 14, 28

**Comment by perazz** [comment]
Added the last couple of tests (16, 29) now all seem to be running. This doesn't mean the test programs are ready for continuous integration (they should return error flags after comparison with expected data), but I'll close this issue for now
