### ISSUE TITLE
Uninitialized variables

### ISSUE THREAD

**Issue by jacobwilliams** [perazz/fitpack#6]
The old code may be assuming that variables got initialized to 0, which is non-standard. When I compile in debug mode with ifort, I get several instances of uninitialized variables being used (e.g., `fp0`, `fpold`, `nplus`). I can submit a patch.

**Comment by perazz** [comment]
Thank you, it seems like most wrappers just clear the working space to 0 (see [here](https://github.com/jbaayen/fitpackpp/blob/master/fitpackpp/BSplineCurve.cpp), for example). 
But I agree it's in the interest of modernization to sort this stuff out. I'm also getting more warnings with fpm build
