### ISSUE TITLE
command line to compile

### ISSUE THREAD

**Issue by Beliavsky** [perazz/fitpack#7]
The current command 

`gfortran src/fitpack_core.f90 src/fitpack_tests.f90 src/fitpack.f90 test/test.f90 -o fitpack_test.exe`

does not work, giving

```
f951.exe: Fatal Error: Cannot open file 'src/fitpack_tests.f90'
compilation terminated.
test/test.f90:2:9:

    2 |     use fitpack_tests
      |         1
Fatal Error: Cannot open module file 'fitpack_tests.mod' for reading at (1): No such file or directory
compilation terminated.
```

It should be

`gfortran src/fitpack_core.f90 test/fitpack_test_data.f90 test/fitpack_tests.f90 src/fitpack.f90 test/test.f90 -o fitpack_test.exe`

**Comment by perazz** [comment]
Thank you, that was left behind - fixed with the latest commit (a simple makefile is also added)
